name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Start dev server
      run: npm start &

    - name: Wait for server to start
      run: |
        while ! nc -z localhost 12506; do sleep 1; done

    - name: Run tests
      run: npm run cy:ci
