name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Start dev server
      run: npm start &

    - name: Wait for server to start
      run: |
        while ! nc -z localhost 12506; do sleep 1; done

    - name: Run tests
      run: npm run cy:ci

    - name: Build and Deploy
      run: |
        npm run build
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.DEPLOY_KEY }}@github.com/${{ github.repository }}
        npm run deploy
